version: 2
jobs:
    build-and-push:
        docker:
            -   image: cimg/base:current
                environment:
                    IMAGE_NAME: he8us/nginx-symfony
        steps:
            - checkout
            - setup_remote_docker

            - run:
                    name: "Build and push Docker image"
                    command: |
                        IMAGE_TAG="1.27.0.${CIRCLE_SHA1:0:7}"
                        
                        docker build -t ${IMAGE_NAME}:${IMAGE_TAG} .

                        if [ "${CIRCLE_BRANCH}" == "master" ]; then
                            docker tag ${IMAGE_NAME}:${IMAGE_TAG} ${IMAGE_NAME}:latest
                        fi
                        echo ${DOCKER_PWD} | docker login -u ${DOCKER_LOGIN} --password-stdin
                        docker push ${IMAGE_NAME}

workflows:
    version: 2
    build-and-push:
        jobs:
            -   build-and-push:
                    context: 'Docker Hub'
                    filters:
                        branches:
                            only: master
